version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db: 
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_DB: dreambnb
  web:
    # replace username/repo:tag with your name and image details
    image: booking
    ports:
      - "7777:7777"
    networks:
      - webnet
    depends_on:
      - redis
      - db
    environment:
      DB_HOST: db
      REDIS_HOST: redis
networks:
  webnet:
